<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Airp.Proxy</RootNamespace>
    <AssemblyName>airp-proxy</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Airp.Infrastructure\Airp.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Airp.Tests" />
  </ItemGroup>

</Project>
